### ISSUE TITLE
Keyed-each style behaviour

### ISSUE THREAD

**Issue by The0mbudsman** [ghostebony/svelte-virtual#22]
Hi,

I'm running into a problem with the virtual grid that's similar to the behaviour seen here https://svelte.dev/tutorial/keyed-each-blocks

I have an input list of card images that the virtual grid is managing, but when I go to filter the input list, the images are not correct, though the correct quantity of images is shown. 
Is there a way to add a key to each of my slot items

     
```
<Grid itemCount={card_list.length} itemHeight={card_width*1.45} itemWidth={card_width} height={1200} marginLeft={10} marginTop={10}>
   <div slot="item" let:index let:style {style}>      
      <Card slug_name={card_list[index]}/>
  </div>
</Grid>
```

**Comment by ghostebony** [comment]
Hi,
this is actually a feature already, but only on the `next` tag releases check if you installed the latest `next` release (currently the latest release is [1.0.0-next.9](https://www.npmjs.com/package/svelte-virtual/v/1.0.0-next.9) and set the `getKey` prop look [here](https://github.com/ghostebony/svelte-virtual#grid)

something like this
```svelte
<Grid ... getKey={(index) => card_list[index].id}>
   <div slot="item" let:index let:style {style}>      
      <Card slug_name={card_list[index]}/>
  </div>
</Grid>
```

**Comment by ghostebony** [comment]
Hi,
this is actually a feature already, but only on the `next` tag releases check if you installed the latest `next` release (currently the latest release is [1.0.0-next.9](https://www.npmjs.com/package/svelte-virtual/v/1.0.0-next.9)) and set the `getKey` prop look [here](https://github.com/ghostebony/svelte-virtual#grid)

something like this
```svelte
<Grid ... getKey={(index) => card_list[index].id}>
   <div slot="item" let:index let:style {style}>      
      <Card slug_name={card_list[index]}/>
  </div>
</Grid>
```

**Comment by The0mbudsman** [comment]
Works perfectly. Thank you!
