### ISSUE TITLE
Svelte 5 support?

### ISSUE THREAD

**Issue by gloriousjob** [ghostebony/svelte-virtual#55]
Hi,

I'm glad this plugin exists as to have multiple items in a row seems to not be a common consideration! I know this plugin has been sitting on @next for a while but are there plans to support Svelte 5? I get errors when trying to migrate to Svelte 5 because of peer dependencies from this library.

**Comment by ghostebony** [comment]
hi! I'm currently migrating all my repos, i will migrate here as soon as I can

**Comment by ghostebony** [comment]
I released a new version but I'm not sure that it will work, can you check on your end?

**Comment by gloriousjob** [comment]
The incompatibility is gone so that's a great improvement. I'll be working on migrating everything I can to runes except maybe this since I think you still use slots. Hopefully no issues with that but it may be a bit before I can report if there's further issues.

**Comment by ghostebony** [comment]
great! I plan a full migration soon.
I believe you can still use slots with runes (just don't change it to snippet)

**Comment by gloriousjob** [comment]
It looks like svelte 5 migration's script moved to snippet and it seems to work. But it also tosses errors about typing to I'll revert it to slots per your concern and the errors.

**Comment by ghostebony** [comment]
just published the [1.0.0-next.19](https://www.npmjs.com/package/svelte-virtual/v/1.0.0-next.19) version with migration to svelte 5

**Comment by gloriousjob** [comment]
Thanks, @ghostebony! I appreciate the snippet support!
